### PR TITLE
Update features supported by SIG-Content

### PR DESCRIPTION
**Pull request by monroegm**
Reviewed and updated all the sections except World Building, Viewport and White Box Tool. Plan to review and update those sections next week.

Signed-off-by: Gavin Monroe <71404632+monroegm@users.noreply.github.com>

### CODE REVIEW

**Comment by hultonha** [comment]
@monroegm World Building will need updates from the Large Worlds Team (tagging @mbalfour-amzn, @mcphedar for visibility).

I've created a separate PR for changes to Viewport and White Box - please see this PR https://github.com/o3de/community/pull/165

Any questions let me know. Thanks!

**Comment by mbalfour-amzn** [comment]
> @monroegm World Building will need updates from the Large Worlds Team (tagging @mbalfour-amzn, @mcphedar for visibility).
> 
> I've created a separate PR for changes to Viewport and White Box - please see this PR #165
> 
> Any questions let me know. Thanks!

@tjmichaels already updated the Terrain section, and there have been no changes to Dynamic Vegetation.

**Comment by chanmosq** [comment]
@monroegm Is this waiting on any other updates to the feature grid, or is it ready to merge?

**Comment by monroegm** [comment]
@chanmosq This is now ready to merge.

**Pull request merged**
