### PR TITLE
Updated the Sig-Core Features JSON for the 2022 October release

### PR DESCRIPTION
**Pull request by lumberyard-employee-dm**
resolves o3de/o3de#12006

Signed-off-by: lumberyard-employee-dm <56135373+lumberyard-employee-dm@users.noreply.github.com>

### CODE REVIEW

**Review by aFinchy — APPROVED** [review]
Looks good to me. Will let another review and approve before I merge.

**Comment by vincent6767** [comment]
Looks good to me!

**Review by vincent6767 — APPROVED** [review]
Looks good to me!

**Comment by vincent6767** [comment]
Hi @amzn-pratikpa Can you help review this so we can merge this by this week? Thanks!

**Comment by amzn-pratikpa** [comment]
Looks good to me - go ahead and merge

**Pull request merged**
